### PR TITLE
[resolves #40] Artifact resources having the same artifactId and version

### LINKED ISSUE #40: Artifact resources having the same artifactId and version but different groupId are serialized in non-deterministic order
Sometimes we get

```
    <artifact name="${io.zipkin.java:zipkin}" />
    <artifact name="${io.zipkin.zipkin2:zipkin}" />
```

and sometimes

```
    <artifact name="${io.zipkin.zipkin2:zipkin}" />
    <artifact name="${io.zipkin.java:zipkin}" />
```

This is caused by the fact that we use given artifact's file name as a key for sorting https://github.com/smartics/smartics-jboss-modules-maven-plugin/blob/smartics-jboss-modules-maven-plugin-2.1.4/src/main/java/de/smartics/maven/plugin/jboss/modules/xml/ModuleXmlBuilder.java#L370

Clearly, we need to append the groupId to make the ordering deterministic also for cases like the above.

I'll send a PR once I find some time.

### PR DESCRIPTION
**Pull request by ppalaga**
but different groupId are serialized in non-deterministic

### CODE REVIEW

**Comment by ppalaga** [comment]
4eeeed3 adresses the problem reported by @jamesnetherton . I have run wfc master build with and saw no issues.

**Comment by jamesnetherton** [comment]
@RobertReiner is it possible to have a new plugin release? 

There's no urgency for it, but it would fix a small issue that we have encountered in one of our projects.

**Comment by RobertReiner** [comment]
Released 2.1.5.
I hope it will get pushed to the public repo soon.

**Comment by jamesnetherton** [comment]
Many thanks for such a fast response!

**Comment by ppalaga** [comment]
@RobertReiner vielen dank!

**Comment by RobertReiner** [comment]
Thanks for all the work you put into it this plugin!

You are welcome / gern geschehen!

**Pull request merged**
